### ISSUE TITLE
Add the `payment` field to `event_procedures`  table

### ISSUE THREAD

**Issue by danielnottingham** [espoo-dev/med_system_backend#128]
goal:
- the `payment` field will be of type `String`
- Possible values will be `health insurance` or `others`
- The current `event_procedures` will have the value `health insurance`
- Update/check all `procedure_events` endpoints

steps:
1) create migration to the new field
1.1 set default value for the field
2) create the class to represent the field values
3) check all entity routes
4) add and adjust tests for new functionality

**Comment by edimossilva** [comment]
Hey, about `create the class to represent the field values`, I think we can only check if the String is included in a list of allowed values, for now, this list would contain only `health insurance` and `others`.

**Comment by danielnottingham** [comment]
> Hey, about `create the class to represent the field values`, I think we can only check if the String is included in a list of allowed values, for now, this list would contain only `health insurance` and `others`.

Today we already use classes to represent a string-type attribute with a given list of values.
We use the `enumarate_it` gem as follows:
- a class with associated values: https://github.com/espoo-dev/med_system_backend/blob/main/app/enumerations/event_procedures/room_types.rb
- and we include it in the model like this: https://github.com/espoo-dev/med_system_backend/blob/main/app/models/event_procedure.rb
- its use gives us several methods to use with these enums
